application: split-back
version: 1
runtime: go
api_version: go1

handlers:
  - url: /static
    secure: always
    login: required
    static_dir: static

  - url: /
    secure: always
    login: required
    static_files: dart/build/web/main.html
    upload: dart/build/web/main.html

  - url: /dart/
    secure: always
    login: required
    static_files: dart/out/web/main.html
    upload: dart/out/web/main.html

  - url: /rest/payIpn
    secure: always
    script: _go_app

  - url: /rest/.*
    secure: always
    login: required
    script: _go_app

  - url: /dart/(.*)
    secure: always
    login: required
    static_files: dart/out/web/\1
    upload: dart/out/web/(.*)
    
  - url: /(.*)
    secure: always
    login: required
    static_files: dart/build/web/\1
    upload: dart/build/web/(.*)
