application: split-back
version: 1
runtime: go
api_version: go1

handlers:
  - url: /static
    secure: always
    login: required
    static_dir: static

  - url: /
    secure: always
    login: required
    static_files: dart/web/out/web/main.html
    upload: dart/web/out/web/main.html

  - url: /rest/.*
    secure: always
    login: required
    script: _go_app

  - url: /(.*)
    secure: always
    login: required
    static_files: dart/web/out/web/\1
    upload: dart/web/out/web/(.*)
