name: splitback
author: Will Moss
description: Bill splitting made easy
dependencies:
  js: ">=0.3.0 <0.4.0"
  polymer: ">=0.15.0 <0.16.0"
  uuid: ">=0.4.0 <0.5.0"

transformers:
- polymer:
    entry_points: web/main.html
